name: bookmyroom
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.5.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
